name = "grom"
version = "6.0.0"
description = "A Gleamy library for the Discord API 🌟"
licenses = ["MIT"]
repository = { type = "github", user = "folospior", repo = "grom" }
internal_modules = [
  "grom/internal/*"
]

[dependencies]
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_time = ">= 1.1.0 and < 2.0.0"
multipart_form = ">= 1.1.0 and < 2.0.0"
status_code = ">= 1.0.0 and < 2.0.0"
gleam_community_colour = ">= 2.0.4 and < 3.0.0"
datebook = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
